apiVersion: v1
clusters:
  - cluster:
      insecure-skip-tls-verify: false
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZUl0R3ZTQ2FhVU13RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBNU1Ea3hOREV5TXpGYUZ3MHpOakE1TURZeE5ERTNNekZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNucmR4VnJTdGd0QjE5T1VFTHdrVCtsdk41cXVDeC9udy9xOHhxL1dLZEdSZkhxYVp3WWxZcU9KTnQKTmpyZWpHY3lPUXEyN3dLS2ZaNlhRZGFvOWx0RXhBVDhHWDdqeU5xSG5kdXVDS0N5aVZ2Q0xkWnFOU1NuR0xSVwoxR3Jla2VBaWNFWU5GMUdFUWQwMEM3bWU3Ung4eTN0UDlpNndhQWQzTmRpK3crVGE3b3JnUmRHMDlVWDJ4MGtpCkNYeTl1NXRUR0pQVDVhd2VMcDdHVjRkZjJLK2NzU1hGbFhOczEwS0pXdEl0c3E2d2tQdEFPUkVlZEliMWJOaUEKRi95NFVYQk1aQ28xYzhVeXBOd3FyZURTdEtWT0hQMTlOV0Z3Z0Foc0p6clZjbXc1akRXRVhhTStwU2d5YlJCQQoyTC81YUdXcDhMd0QvZjFKNXNRQ1dDRWZoMGpCQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUMWtIKzAwK2tXNVRwQW5xbVVxak9ZTTYzS3JUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQlh5SHVLN1JJZwpRcmlrd05vc0k2MEJzUVczbFJ1WkJiYWwxaGlmMWRWTmoxd25jS09GYU4rVTVtYUhSWG1ibFZuNUZNQmZaamhiCkg1UVB2UEg2dy84VkxiWVFyc2NzRFpLRGxwU096ZkJMaHRoV2FPNWJ2a24veHVOWDlwTTZISVdrS2E4WVlXdlcKRC9nR1dsNExWRnZtSmpXc1hMWEZOTlFyYlpZRjdkSWxOMGxyanZBT1F3dDk0dnJEMnFGZkwyYXp0UFNRZi9kYwovU3lZbXl3VmhqcHVLczZ5cTJoL0dOY21ySndJcWhlVUM4Q1Z6ajByRDM2V1VEYlFScTZYWHNXMlBtS2IwVlZiCmNGWU83YjVSeDMyajFlK1paK1NTV0lSeStFb1FyWWYySS8rSSswVjJNb3J6cGFOVVIrdGJoTTZHVGt5STN5YjUKUlJrbFJjY3kvKzRyCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://hcp-24ae9138-b3d4-467b-962c-2987666c656c.spot.rackspace.com/
    name: helm
contexts:
  - context:
      cluster: helm
      namespace: default
      user: ngpc-user-kube-ops-helm
    name: kube-ops-helm
  - context:
      cluster: helm
      namespace: default
      user: oidc-kube-ops-helm
    name: kube-ops-helm-oidc
current-context: kube-ops-helm
kind: Config
preferences: {}
users:
  - name: ngpc-user-kube-ops-helm
    user:
      token: >-
        eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkNYQ25nd1NFS0JWQl9DbWxvalo0eCJ9.eyJncm91cCI6ImNsb3Vkc3BhY2UtYWRtaW4iLCJnaXZlbl9uYW1lIjoiU2FtZWgiLCJmYW1pbHlfbmFtZSI6IkFtbWFyIiwibmlja25hbWUiOiJtci5zYW1lNy5hbW1hciIsIm5hbWUiOiJTYW1laCBBbW1hciIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NKaHFtVnEwRDdJNlNGNmpYY242VHhCMVJ5ZTk1YlI5c3JVTnNPNjZCOUtyU1FWOUNxdz1zOTYtYyIsInVwZGF0ZWRfYXQiOiIyMDI2LTA5LTE3VDE3OjU3OjQzLjQwMVoiLCJlbWFpbCI6Im1yLnNhbWU3LmFtbWFyQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJpc3MiOiJodHRwczovL2xvZ2luLnNwb3QucmFja3NwYWNlLmNvbS8iLCJhdWQiOiJtd0czbFVNVjhLeWVNcUhlNGZKNUJiM25NMXZCdlJOYSIsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTA4NTYwNDQxNzAyMTQ1NTc3NTQzIiwiaWF0IjoxNzg5NjY4NDg2LCJleHAiOjE3ODk5Mjc2ODYsInNpZCI6IjE5aG9SUGxvbkZJcGJVZjR0OFQyS3IzNkNtaE9hOTlkIiwibm9uY2UiOiJhbko1VWpWSlJUbDRja1l3YVVsSmRqTklNbGxZTjJGZlFYTkNWVkZRVG1kQmRGbDJWekZEUkVkU1JBPT0iLCJvcmdfaWQiOiJvcmdfTzlRMGFDaDhCdzJ2WG1oQiJ9.GKZKNJB3Er2LWkGKpgEonmcZpGlvh1wjL8Q-zYy5kYhOeqZTM6bBEJ5vKIN1YvNIf2puS_iWNljc3S0W3sx8KJg74xuocoYIIzP_YvgLkJlSXaQXGgHL61C6r2pmtC9p-RkJwo_QveAYMzNkJpV7XTRp3zPya5jbF1rSTmgI3Yv05mDWm2r28Rb2IPNy_0FBTgH7m7nyPOtZxMUVTYWAkbwl3ed1hfFyBj0yBi0x-0QqGFu9_n5_wXJptZQLrqHXu3gwiyrTZSOUrfun5uzF4BqoWmpfCuW5-_ML4_0BuGjDBn5Ga3c7q1D9ag0dSsmTyrNlRzosmdFHJahn1zAVHQ
  - name: oidc-kube-ops-helm
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - oidc-login
          - get-token
          - "--oidc-issuer-url=https://login.spot.rackspace.com/"
          - "--oidc-client-id=mwG3lUMV8KyeMqHe4fJ5Bb3nM1vBvRNa"
          - "--oidc-extra-scope=openid"
          - "--oidc-extra-scope=profile"
          - "--oidc-extra-scope=email"
          - "--oidc-auth-request-extra-params=organization=org_O9Q0aCh8Bw2vXmhB"
          - "--token-cache-dir=~/.kube/cache/oidc-login/org_O9Q0aCh8Bw2vXmhB"
        command: kubectl
        env: null
        interactiveMode: IfAvailable
        provideClusterInfo: false
