apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  app.properties: |
    log.level=info
    feature.banner={{ .Values.features.banner }}
    feature.darkmode={{ .Values.features.darkmode }}