apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: aks-store
data:
  RABBITMQ_DEFAULT_USER: dXNlcm5hbWU=
  RABBITMQ_DEFAULT_PASS: cGFzc3dvcmQ=
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: aks-store
spec:
  serviceName: rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:4.3.2-management-alpine
          ports:
            - containerPort: 5672
            - containerPort: 15672
          envFrom:
            - secretRef:
                name: rabbitmq-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: aks-store
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
