apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: aks-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: ghcr.io/azure-samples/aks-store-demo/product-service:2.2.0
          ports:
            - containerPort: 3002
          env:
            - name: AI_SERVICE_URL
              value: "http://ai-service:5001/"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: aks-store
spec:
  selector:
    app: product-service
  ports:
    - port: 3002
      targetPort: 3002
